server:
  port: 8000
  servlet:
    context-path: /kafka
spring:
  kafka:
    consumer:
      group-id: 1
    bootstrap-servers: localhost:9092
  feign:
    client:
      config:
        default:
          connectTimeout: 10000
          readTimeout: 1000


