version: "3"

services:

  postgres:
    image: postgres:9.6
    domainname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTRGES_PASSWORD=123
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
     image: boxfuse/flyway
     command: -url-jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=123 connectRetries=60 migrate
     volumes:
       - ./auth-service/src/main/resources/db/migration/V1__init.sql:/flyway/sql
    depends_on:
        - postgres

  redis:
      image: 'bitnami/redis:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - 6379:6379
