server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      cache:
        default:
          expire-time: 700000000
        user:
          expire-time: 100
          name: "Cart"
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false